# Servicios conocidos susceptibles a subdomain takeover (CNAME dangling).

TAKEOVER_FINGERPRINTS = {
    "github.io": "GitHub Pages",
    "herokuapp.com": "Heroku",
    "herokudns.com": "Heroku",
    "azurewebsites.net": "Azure",
    "cloudapp.net": "Azure",
    "blob.core.windows.net": "Azure Blob",
    "s3.amazonaws.com": "AWS S3",
    "amazonaws.com": "AWS",
    "cloudfront.net": "CloudFront",
    "shopify.com": "Shopify",
    "myshopify.com": "Shopify",
    "fastly.net": "Fastly",
    "pantheonsite.io": "Pantheon",
    "zendesk.com": "Zendesk",
    "ghost.io": "Ghost",
    "surge.sh": "Surge",
    "bitbucket.io": "Bitbucket",
    "readme.io": "ReadMe",
    "statuspage.io": "Statuspage",
    "uservoice.com": "UserVoice",
    "wordpress.com": "WordPress",
    "wpengine.com": "WP Engine",
    "unbounce.com": "Unbounce",
    "tumblr.com": "Tumblr",
    "feedpress.me": "FeedPress",
}
